### ISSUE TITLE
Crash when control parent is changed mid draw

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#424]
> 18:02:10.9811 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blish_HUD.Controls.Control.get_AbsoluteBounds() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Control.cs:line 399
   at Blish_HUD.SpriteBatchExtensions.DrawOnCtrl(SpriteBatch spriteBatch, Control ctrl, Texture2D texture, Rectangle destinationRectangle, Nullable`1 sourceRectangle) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\_Extensions\SpriteBatchExtensions.cs:line 88
   at Blish_HUD.Controls.Dropdown.Paint(SpriteBatch spriteBatch, Rectangle bounds) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Dropdown.cs:line 282
   at Blish_HUD.Controls.Control.Draw(SpriteBatch spriteBatch, Rectangle drawBounds, Rectangle scissor) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Control.cs:line 739
   at Blish_HUD.Controls.Container.PaintChildren(SpriteBatch spriteBatch, Rectangle bounds, Rectangle scissor) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 273
   at Blish_HUD.Controls.Container.Paint(SpriteBatch spriteBatch, Rectangle bounds) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 250
   at Blish_HUD.Controls.Control.Draw(SpriteBatch spriteBatch, Rectangle drawBounds, Rectangle scissor) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Control.cs:line 739
   at Blish_HUD.Controls.Container.PaintChildren(SpriteBatch spriteBatch, Rectangle bounds, Rectangle scissor) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 273
   at Blish_HUD.Controls.Container.Paint(SpriteBatch spriteBatch, Rectangle bounds) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Container.cs:line 250
   at Blish_HUD.Controls.Control.Draw(SpriteBatch spriteBatch, Rectangle drawBounds, Rectangle scissor) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Controls\Control.cs:line 739
   at Blish_HUD.GraphicsService.Render(GameTime gameTime, SpriteBatch spriteBatch) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\GraphicsService.cs:line 211
   at Blish_HUD.BlishHud.Draw(GameTime gameTime) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\BlishHud.cs:line 140
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Blish_HUD.Program.Main(String[] args) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Program.cs:line 64

**Comment by dlamkins** [comment]
Closed by #425
