### ISSUE TITLE
The GPU device instance has been suspended.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#464]
We do not properly recover from this issue like we should.  Causes all further texture loading to fail and the application to crash.  This is a very rare error.  

> 00:55:01.9845 | WARN  | BhModule.Community.Pathing.Utility.AttributeParsingUtil | Failed to load texture.
System.InvalidOperationException: This image format is not supported ---> SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
>   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSetData[T](Int32 level, T[] data, Int32 startIndex, Int32 elementCount)
   at Microsoft.Xna.Framework.Graphics.Texture2D.SetData[T](T[] data)
   at Microsoft.Xna.Framework.Graphics.Texture2D.PlatformFromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(GraphicsDevice graphicsDevice, Stream stream)
   at Blish_HUD.TextureUtil.FromStreamPremultiplied(GraphicsDevice graphics, Stream stream) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\_Utils\TextureUtil.cs:line 15
   at BhModule.Community.Pathing.Utility.AttributeParsingUtil.<GetValueAsTextureAsync>d__19.MoveNext() in C:\Users\dade\source\repos\Pathing\Utility\AttributeParsingUtil.cs:line 110

**Comment by dlamkins** [comment]
0x887A0005  😬

**Comment by dartungar** [comment]
This error plagues me constantly. Like, BHud crashes every 30-60 minutes.
Note that I am using integrated Intel Iris XE graphics.

**Comment by jocropsey** [comment]
I've got this issue too, it drives me nuts with its constant crashing. My graphics card is AMD Radeon RX 

EDIT: in case anyone else has this problem, updating my graphics driver fixed it!
