### ISSUE TITLE
Crash when there is no audio device.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#498]
Blish HUD crashes if there is no audio device.

```
Blish HUD v0.11.0+Branch.tags-v0.11.0.Sha.cfbdea1a331bbc903ea5954cfc03c9d0f62d776b
10:41:39.1509 | INFO  | Blish_HUD.Program | Running Build "Branch.tags-v0.11.0.Sha.cfbdea1a331bbc903ea5954cfc03c9d0f62d776b"
10:41:40.1894 | INFO  | Blish_HUD.SettingsService | Preparing default settings file.
10:41:40.8757 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
CSCore.CoreAudioAPI.CoreAudioAPIException (0x80070490): IMMDeviceEnumerator::GetDefaultAudioEndpoint caused an error: 0x80070490, "Element not found.".
   at CSCore.CoreAudioAPI.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role)
   at Blish_HUD.GameIntegration.AudioIntegration.Load() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\GameIntegration\AudioIntegration.cs:line 73
   at Blish_HUD.GameService.DoLoad() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\GameService.cs:line 43
   at Blish_HUD.BlishHud.BeginRun() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\BlishHud.cs:line 93
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Blish_HUD.Program.Main(String[] args) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\Program.cs:line 74
```

REF: https://discord.com/channels/531175899588984842/534492173362528287/895420604931510283

**Comment by dlamkins** [comment]
Fixed in #497
