### ISSUE TITLE
Start with disabled API reliant features when API isn't accessible

### ISSUE THREAD

**Issue by Ryuichiro** [blish-hud/Blish-HUD#622]
Blish crashed on startup because it can't reach the Web API, which is `Temporarily disabled to avoid classified End of Dragons information escaping from the vault of forbidden spoilers. See you in Cantha!`

```Blish HUD v0.11.7+Branch.tags-v0.11.7.Sha.0c709c76cb502d310f2964dca92ce770e533dae2
04:28:39.5171 | INFO  | Blish_HUD.Program | Running Build "Branch.tags-v0.11.7.Sha.0c709c76cb502d310f2964dca92ce770e533dae2"
04:28:39.5171 | INFO  | Blish_HUD.Program | Launched from "D:\Software\Blish HUD" with args "".
04:28:41.7750 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "markers" ("D:\Software\Blish HUD\Settings\markers") was registered.
04:28:42.3751 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "timers" ("D:\Software\Blish HUD\Settings\timers") was registered.
04:28:42.7759 | INFO  | Blish_HUD.Modules.Managers.DirectoriesManager | Directory "events" ("D:\Software\Blish HUD\Settings\events") was registered.
04:28:43.1287 | FATAL | Blish_HUD.DebugService | Blish HUD encountered a fatal crash!
Gw2Sharp.WebApi.Exceptions.ServiceUnavailableException: <h1>Status Code 503</h1><p>Temporarily disabled to avoid classified End of Dragons information escaping from the vault of forbidden spoilers. See you in Cantha!</p>
   at Gw2Sharp.WebApi.Middleware.ExceptionMiddleware.<>c__DisplayClass1_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gw2Sharp.WebApi.Middleware.RequestSplitterMiddleware.<>c__DisplayClass4_0.<<OnRequestAsync>g__ExecAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.<RequestGetAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gw2Sharp.WebApi.Caching.BaseCacheMethod.<>c__DisplayClass4_0.<<GetOrUpdateAsync>g__ExecAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gw2Sharp.WebApi.Middleware.CacheMiddleware.<OnEndpointRequestAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gw2Sharp.WebApi.Http.WebApiRequest.<ExecuteAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Gw2Sharp.WebApi.V2.Clients.BaseEndpointBulkAllClient`2.<GetAsync>d__2.MoveNext()
```

**Comment by dlamkins** [comment]
Hello, yes, we've already got fixes for most of these issues.

Please remove any of the following modules from your modules folder until either the API comes back up (in ~24 hours):
- StreamOut
- EventTable

Remove them from this folder: \Documents\Guild Wars 2\addons\blishhud\modules

There is a new version of both of these modules which resolves this issue.  Once you've deleted them from your modules folder, you can download the latest version from the repo safely.

Based on your log, it appears to have the old event table module.

**Comment by dlamkins** [comment]
The API should hopefully return sometime tomorrow.  You can track the status here:

https://status.gw2efficiency.com/
