### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/Blish-HUD#808]
We still occasionally see an error with Ookii dialogs on some systems.  I'm unsure of what is missing on these systems, but it could be good for us to do either:
- remove the dependency and put out our own mini diag window of our own.
- provide an alternative method of displaying the error if we catch the exception when attempting to show the window.

```
System.EntryPointNotFoundException: Unable to find an entry point named 'TaskDialogIndirect' in DLL 'comctl32.dll'.
   at Ookii.Dialogs.WinForms.NativeMethods.TaskDialogIndirect(TASKDIALOGCONFIG& pTaskConfig, Int32& pnButton, Int32& pnRadioButton, Boolean& pfVerificationFlagChecked)
   at Ookii.Dialogs.WinForms.TaskDialog.ShowDialog(IntPtr owner) in D:\a\ookii-dialogs-winforms\ookii-dialogs-winforms\src\Ookii.Dialogs.WinForms\TaskDialog.cs:line 1132
   at Ookii.Dialogs.WinForms.TaskDialog.ShowDialog() in D:\a\ookii-dialogs-winforms\ookii-dialogs-winforms\src\Ookii.Dialogs.WinForms\TaskDialog.cs:line 1065
   at Blish_HUD.Debug.Contingency.NotifyContingency(String key, String title, String description, String url, ValueTuple`2[] extraActions) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Debug\Contingency.cs:line 56
   at Blish_HUD.Debug.Contingency.NotifyWin32AccessDenied() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\Debug\Contingency.cs:line 67
   at Blish_HUD.GameIntegration.Gw2InstanceIntegration.set_Gw2Process(Process value) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\GameIntegration\Gw2InstanceIntegration.cs:line 52
   at Blish_HUD.GameIntegration.Gw2InstanceIntegration.TryAttachToGw2() in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\GameIntegration\Gw2InstanceIntegration.cs:line 231
   at Blish_HUD.GameIntegration.Gw2InstanceIntegration.Update(GameTime gameTime) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\GameIntegration\Gw2InstanceIntegration.cs:line 365
   at Blish_HUD.GameService.DoUpdate(GameTime gameTime) in D:\a\Blish-HUD\Blish-HUD\Blish HUD\GameServices\GameService.cs:line 77
```

**Comment by dlamkins** [comment]
Replaced in https://github.com/blish-hud/Blish-HUD/pull/829/files

**Comment by dlamkins** [comment]
(an idea if we ever want to come back to this: https://discord.com/channels/531175899588984842/536970543736291346/1091062901088993291)
